### ISSUE TITLE
Code blocks overlap with headings

### ISSUE THREAD

**Issue by aaronduino** [jez/tufte-pandoc-css#1]
Code blocks overlap with headings above them.

Expected:
<img width="526" alt="screen shot 2017-11-09 at 4 00 25 pm" src="https://user-images.githubusercontent.com/16829510/32636022-c9701a2c-c567-11e7-9155-d32baf30c65b.png">

Actual:
<img width="496" alt="screen shot 2017-11-09 at 3 59 43 pm" src="https://user-images.githubusercontent.com/16829510/32636021-c952f604-c567-11e7-96b0-209dd247bb01.png">

The problematic code is found in [line 55 of pandoc.css](https://github.com/jez/tufte-pandoc-css/blob/2601ce86d0da87e0afe49918ad5ada9ec6e55b84/pandoc.css#L55)

This issue can be resolved by changing:
```
margin: -0.7rem -1.4rem;
```

to:
```
margin-left: -0.7rem;
```

---

I would typically just open a PR for this, but I am not sure about which tufte-css repo to sumbit changes to.

Some other repos affected (afaik):
* [markdown2tufte](https://github.com/schollz/markdown2tufte/blob/daa0acaf6413800dff2d0f0b1778cec5c72f3f4b/markdown2tufte/assets/pandoc.css#L55)

Thanks for this great project, btw.

**Comment by jez** [comment]
Oh wow, thanks for catching this!

I'm trying to see what the best way to fix this is. The CSS change you posted works for the pre-after-heading use case, but it also adds too much vertical space in the pre-between-paragraph use case.

In the mean time, a work around is to put an empty `<p></p>` between a header and a code block.

**Comment by aaronduino** [comment]
Could you use a selector specific to code blocks after headings?

I think that [adjacent selectors](http://www.w3.org/TR/CSS2/selector.html#adjacent-selectors) let you do this.

**Comment by aaronduino** [comment]
I'm not sure about browser compatibility, though.

**Comment by jez** [comment]
Yep, that's definitely one of the solutions I'm considering.

The other is actually overriding/submitting a PR to tufte.css to set `margin-bottom: 1.4rem` on `<h2>` and `<h3>` tags. That would solve this problem more generally.

**Comment by aaronduino** [comment]
That's a better solution. 

I can submit a PR for that in the morning (I'm on mobile rn)

**Comment by jez** [comment]
https://github.com/edwardtufte/tufte-css/pull/126

**Comment by jez** [comment]
I pre-emptively applied the upstream patch solution in 67fe169, so I'm going to close this for now. I'll revert that commit if tufte-css chooses to include the patch.
